from pathlib import Path

VEHICLE_MAKE = ['Abarth', 'Alfa Romeo', 'Aston Martin', 'Audi', 'BMW', 'Bentley',
       'Chevrolet', 'Chrysler', 'Citroen', 'DS', 'Dacia', 'Daihatsu',
       'Dodge', 'Ferrari', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Infiniti',
       'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Lamborghini', 'Land Rover',
       'Lexus', 'Lotus', 'MG', 'MINI', 'Maserati', 'Mazda', 'McLaren',
       'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Peugeot', 'Porsche',
       'Renault', 'Rolls-Royce', 'Rover', 'SEAT', 'SKODA', 'Saab',
       'Smart', 'Ssangyong', 'Subaru', 'Suzuki', 'Tesla', 'Toyota',
       'Vauxhall', 'Volkswagen', 'Volvo']
VEHICLE_MAKE = [f"Make-{m}" for m in VEHICLE_MAKE]

VEHICLE_MODEL = ['Abarth_124 Spider', 'Abarth_595', 'Abarth_595C', 'Alfa Romeo_159',
       'Alfa Romeo_Brera', 'Alfa Romeo_GT', 'Alfa Romeo_Giulia',
       'Alfa Romeo_Giulietta', 'Alfa Romeo_MiTo', 'Alfa Romeo_Spider',
       'Alfa Romeo_Stelvio', 'Aston Martin_DB11', 'Aston Martin_DB9',
       'Aston Martin_DBS', 'Audi_A1', 'Audi_A2', 'Audi_A3',
       'Audi_A3 Cabriolet', 'Audi_A4', 'Audi_A4 Allroad', 'Audi_A4 Avant',
       'Audi_A4 Cabriolet', 'Audi_A5', 'Audi_A5 Cabriolet', 'Audi_A6',
       'Audi_A6 Allroad', 'Audi_A6 Avant', 'Audi_A6 Saloon',
       'Audi_A6 Unspecified', 'Audi_A7', 'Audi_A8', 'Audi_Allroad',
       'Audi_Q2', 'Audi_Q3', 'Audi_Q5', 'Audi_Q7', 'Audi_R8',
       'Audi_RS Q3', 'Audi_RS3', 'Audi_RS4 Avant', 'Audi_RS4 Saloon',
       'Audi_RS5', 'Audi_RS6 Avant', 'Audi_RS7', 'Audi_S1', 'Audi_S3',
       'Audi_S4', 'Audi_S4 Avant', 'Audi_S4 Cabriolet', 'Audi_S5',
       'Audi_SQ5', 'Audi_SQ7', 'Audi_TT', 'Audi_TT RS', 'Audi_TTS',
       'BMW_1 Series', 'BMW_2 Series', 'BMW_2 Series Active Tourer',
       'BMW_2 Series Gran Tourer', 'BMW_3 Series',
       'BMW_3 Series Gran Turismo', 'BMW_4 Series',
       'BMW_4 Series Gran Coupe', 'BMW_5 Series',
       'BMW_5 Series Gran Turismo', 'BMW_6 Series',
       'BMW_6 Series Gran Coupe', 'BMW_6 Series Gran Turismo',
       'BMW_7 Series', 'BMW_Alpina D3 Bi-Turbo', 'BMW_M2', 'BMW_M3',
       'BMW_M4', 'BMW_M5', 'BMW_M6', 'BMW_M6 Gran Coupe', 'BMW_X1',
       'BMW_X2', 'BMW_X3', 'BMW_X4', 'BMW_X5', 'BMW_X5M', 'BMW_X6',
       'BMW_Z3', 'BMW_Z4', 'BMW_Z4M', 'BMW_i3', 'BMW_i8',
       'Bentley_Arnage', 'Bentley_Bentayga', 'Bentley_Continental',
       'Bentley_Flying Spur', 'Bentley_Mulsanne', 'Chevrolet_Aveo',
       'Chevrolet_Captiva', 'Chevrolet_Cruze', 'Chevrolet_Kalos',
       'Chevrolet_Lacetti', 'Chevrolet_Matiz', 'Chevrolet_Orlando',
       'Chevrolet_Spark', 'Chevrolet_Trax', 'Chrysler_300C',
       'Chrysler_Crossfire', 'Chrysler_Grand Voyager',
       'Chrysler_PT Cruiser', 'Chrysler_Voyager', 'Chrysler_Ypsilon',
       'Citroen_Berlingo', 'Citroen_Berlingo Multispace',
       'Citroen_C-Crosser', 'Citroen_C1', 'Citroen_C2', 'Citroen_C3',
       'Citroen_C3 Aircross', 'Citroen_C3 Picasso', 'Citroen_C4',
       'Citroen_C4 Cactus', 'Citroen_C4 Picasso', 'Citroen_C5',
       'Citroen_C8', 'Citroen_DS3', 'Citroen_DS3 Cabrio', 'Citroen_DS4',
       'Citroen_DS5', 'Citroen_Grand C4 Picasso', 'Citroen_Saxo',
       'Citroen_SpaceTourer', 'Citroen_Xsara Picasso', 'DS_3',
       'DS_3 Cabrio', 'DS_4', 'DS_4 Crossback', 'DS_5', 'Dacia_Duster',
       'Dacia_Logan MCV', 'Dacia_Sandero', 'Dacia_Sandero Stepway',
       'Daihatsu_Sirion', 'Daihatsu_Terios', 'Dodge_Caliber',
       'Dodge_Nitro', 'Ferrari_360', 'Ferrari_458', 'Ferrari_488',
       'Ferrari_599', 'Ferrari_California', 'Ferrari_F12berlinetta',
       'Ferrari_F430', 'Ferrari_FF', 'Fiat_124 Spider', 'Fiat_500',
       'Fiat_500C', 'Fiat_500L', 'Fiat_500X', 'Fiat_Bravo', 'Fiat_Doblo',
       'Fiat_Fullback', 'Fiat_Grande Punto', 'Fiat_Panda', 'Fiat_Punto',
       'Fiat_Punto Evo', 'Fiat_Qubo', 'Fiat_Tipo', 'Ford_B-Max',
       'Ford_C-Max', 'Ford_EcoSport', 'Ford_Edge', 'Ford_Fiesta',
       'Ford_Focus', 'Ford_Focus C-Max', 'Ford_Focus CC', 'Ford_Fusion',
       'Ford_Galaxy', 'Ford_Grand C-Max', 'Ford_Grand Tourneo Connect',
       'Ford_Ka', 'Ford_Ka+', 'Ford_Kuga', 'Ford_Mondeo', 'Ford_Mustang',
       'Ford_Ranger', 'Ford_S-Max', 'Ford_Streetka',
       'Ford_Tourneo Connect', 'Ford_Tourneo Custom',
       'Ford_Transit Custom', 'Honda_Accord', 'Honda_CR-V', 'Honda_CR-Z',
       'Honda_Civic', 'Honda_FR-V', 'Honda_HR-V', 'Honda_Insight',
       'Honda_Jazz', 'Honda_NSX', 'Honda_S2000', 'Hyundai_Amica',
       'Hyundai_Coupe', 'Hyundai_Getz', 'Hyundai_Ioniq', 'Hyundai_Kona',
       'Hyundai_Matrix', 'Hyundai_Santa Fe', 'Hyundai_Tucson',
       'Hyundai_Veloster', 'Hyundai_i10', 'Hyundai_i20', 'Hyundai_i30',
       'Hyundai_i40', 'Hyundai_i800', 'Hyundai_ix20', 'Hyundai_ix35',
       'Infiniti_FX', 'Infiniti_Q30', 'Infiniti_Q50', 'Infiniti_Q60',
       'Infiniti_Q70', 'Isuzu_D-Max', 'Isuzu_Rodeo', 'Jaguar_E-PACE',
       'Jaguar_F-PACE', 'Jaguar_F-Type', 'Jaguar_S-Type', 'Jaguar_X-Type',
       'Jaguar_XE', 'Jaguar_XF', 'Jaguar_XJ', 'Jaguar_XK', 'Jaguar_XK8',
       'Jaguar_XKR', 'Jeep_Cherokee', 'Jeep_Compass',
       'Jeep_Grand Cherokee', 'Jeep_Patriot', 'Jeep_Renegade',
       'Jeep_Wrangler', 'Kia_Carens', "Kia_Cee'd", 'Kia_Niro',
       'Kia_Optima', 'Kia_Picanto', "Kia_Pro_Cee'd", 'Kia_Rio',
       'Kia_Sedona', 'Kia_Sorento', 'Kia_Soul', 'Kia_Sportage',
       'Kia_Stinger', 'Kia_Stonic', 'Kia_Venga', 'Lamborghini_Aventador',
       'Lamborghini_Gallardo', 'Lamborghini_Huracan',
       'Land Rover_Defender 110', 'Land Rover_Defender 90',
       'Land Rover_Discovery', 'Land Rover_Discovery 3',
       'Land Rover_Discovery 4', 'Land Rover_Discovery Sport',
       'Land Rover_Freelander', 'Land Rover_Freelander 2',
       'Land Rover_Range Rover', 'Land Rover_Range Rover Evoque',
       'Land Rover_Range Rover Sport', 'Land Rover_Range Rover Velar',
       'Lexus_CT', 'Lexus_CT 200h', 'Lexus_GS 300', 'Lexus_GS 450h',
       'Lexus_IS', 'Lexus_IS 200', 'Lexus_IS 220d', 'Lexus_IS 250',
       'Lexus_IS 300', 'Lexus_LC 500', 'Lexus_LS 430', 'Lexus_LS 460',
       'Lexus_NX', 'Lexus_NX 300h', 'Lexus_RC', 'Lexus_RC 300h',
       'Lexus_RX', 'Lexus_RX 300', 'Lexus_RX 350', 'Lexus_RX 400h',
       'Lexus_RX 450h', 'Lotus_Evora', 'Lotus_Exige', 'MG_GS', 'MG_MG3',
       'MG_MGF', 'MG_TF', 'MG_ZS', 'MG_ZT', 'MINI_Clubman',
       'MINI_Clubvan', 'MINI_Convertible', 'MINI_Countryman',
       'MINI_Coupe', 'MINI_Hatch', 'MINI_Paceman', 'MINI_Roadster',
       'Maserati_Ghibli', 'Maserati_GranCabrio', 'Maserati_Granturismo',
       'Maserati_Levante', 'Maserati_Quattroporte', 'Mazda_CX-3',
       'Mazda_CX-5', 'Mazda_CX-7', 'Mazda_MX-5', 'Mazda_MX-5 RF',
       'Mazda_Mazda2', 'Mazda_Mazda3', 'Mazda_Mazda5', 'Mazda_Mazda6',
       'Mazda_RX-8', 'McLaren_12C', 'McLaren_570GT', 'McLaren_570S',
       'McLaren_650S', 'McLaren_720S', 'Mercedes-Benz_A Class',
       'Mercedes-Benz_Amg Gt', 'Mercedes-Benz_B Class',
       'Mercedes-Benz_C Class', 'Mercedes-Benz_CL',
       'Mercedes-Benz_CLA Class', 'Mercedes-Benz_CLC Class',
       'Mercedes-Benz_CLK', 'Mercedes-Benz_CLS', 'Mercedes-Benz_E Class',
       'Mercedes-Benz_G Class', 'Mercedes-Benz_GL Class',
       'Mercedes-Benz_GLA Class', 'Mercedes-Benz_GLC Class',
       'Mercedes-Benz_GLE Class', 'Mercedes-Benz_GLS Class',
       'Mercedes-Benz_M Class', 'Mercedes-Benz_R Class',
       'Mercedes-Benz_S Class', 'Mercedes-Benz_SL Class',
       'Mercedes-Benz_SLC', 'Mercedes-Benz_SLK', 'Mercedes-Benz_SLS',
       'Mercedes-Benz_V Class', 'Mercedes-Benz_Viano',
       'Mercedes-Benz_Vito', 'Mercedes-Benz_X Class', 'Mitsubishi_ASX',
       'Mitsubishi_Colt', 'Mitsubishi_Colt Cabriolet',
       'Mitsubishi_Eclipse Cross', 'Mitsubishi_L200', 'Mitsubishi_Lancer',
       'Mitsubishi_Mirage', 'Mitsubishi_Outlander', 'Mitsubishi_Shogun',
       'Mitsubishi_Shogun Sport', 'Nissan_350 Z', 'Nissan_370 Z',
       'Nissan_Almera', 'Nissan_Almera Tino', 'Nissan_Elgrand',
       'Nissan_GT-R', 'Nissan_Juke', 'Nissan_Leaf', 'Nissan_Micra',
       'Nissan_Micra C+C', 'Nissan_Murano', 'Nissan_Navara',
       'Nissan_Note', 'Nissan_Pathfinder', 'Nissan_Pixo',
       'Nissan_Primera', 'Nissan_Pulsar', 'Nissan_Qashqai',
       'Nissan_Qashqai+2', 'Nissan_X-Trail', 'Peugeot_1007',
       'Peugeot_107', 'Peugeot_108', 'Peugeot_2008', 'Peugeot_206',
       'Peugeot_206 CC', 'Peugeot_206 SW', 'Peugeot_207',
       'Peugeot_207 CC', 'Peugeot_207 SW', 'Peugeot_208', 'Peugeot_3008',
       'Peugeot_307 CC', 'Peugeot_307 SW', 'Peugeot_308',
       'Peugeot_308 CC', 'Peugeot_308 SW', 'Peugeot_4007', 'Peugeot_407',
       'Peugeot_407 SW', 'Peugeot_5008', 'Peugeot_508', 'Peugeot_508 SW',
       'Peugeot_807', 'Peugeot_Expert Tepee', 'Peugeot_Partner Tepee',
       'Peugeot_RCZ', 'Peugeot_Traveller', 'Porsche_718 Boxster',
       'Porsche_718 Cayman', 'Porsche_911', 'Porsche_Boxster',
       'Porsche_Cayenne', 'Porsche_Cayman', 'Porsche_Macan',
       'Porsche_Panamera', 'Renault_Captur', 'Renault_Clio',
       'Renault_Grand Espace', 'Renault_Grand Modus',
       'Renault_Grand Scenic', 'Renault_Kadjar', 'Renault_Kangoo',
       'Renault_Koleos', 'Renault_Laguna', 'Renault_Megane',
       'Renault_Modus', 'Renault_Scenic', 'Renault_Scenic Xmod',
       'Renault_Trafic', 'Renault_Twingo', 'Renault_Wind', 'Renault_Zoe',
       'Rolls-Royce_Dawn', 'Rolls-Royce_Ghost', 'Rolls-Royce_Phantom',
       'Rolls-Royce_Wraith', 'Rover_75', 'SEAT_Alhambra', 'SEAT_Altea',
       'SEAT_Altea XL', 'SEAT_Arona', 'SEAT_Ateca', 'SEAT_Exeo',
       'SEAT_Ibiza', 'SEAT_Leon', 'SEAT_Mii', 'SEAT_Toledo',
       'SKODA_Citigo', 'SKODA_Fabia', 'SKODA_Karoq', 'SKODA_Kodiaq',
       'SKODA_Octavia', 'SKODA_Rapid', 'SKODA_Rapid Spaceback',
       'SKODA_Roomster', 'SKODA_Superb', 'SKODA_Yeti', 'Saab_9-3',
       'Saab_9-5', 'Smart_Roadster', 'Smart_forfour', 'Smart_fortwo',
       'Ssangyong_Korando', 'Ssangyong_Musso', 'Ssangyong_Rexton',
       'Ssangyong_Tivoli', 'Ssangyong_Tivoli XLV', 'Ssangyong_Turismo',
       'Subaru_BRZ', 'Subaru_Forester', 'Subaru_Impreza', 'Subaru_Legacy',
       'Subaru_Levorg', 'Subaru_Outback', 'Subaru_WRX STI', 'Subaru_XV',
       'Suzuki_Alto', 'Suzuki_Baleno', 'Suzuki_Celerio',
       'Suzuki_Grand Vitara', 'Suzuki_Ignis', 'Suzuki_Jimny',
       'Suzuki_SX4', 'Suzuki_SX4 S-Cross', 'Suzuki_Splash',
       'Suzuki_Swift', 'Suzuki_Vitara', 'Tesla_Model S', 'Tesla_Model X',
       'Toyota_AYGO', 'Toyota_Alphard', 'Toyota_Auris', 'Toyota_Avensis',
       'Toyota_C-HR', 'Toyota_Corolla', 'Toyota_Corolla Verso',
       'Toyota_Estima', 'Toyota_GT86', 'Toyota_Hilux',
       'Toyota_Land Cruiser', 'Toyota_MR2', 'Toyota_PROACE Verso',
       'Toyota_Previa', 'Toyota_Prius', 'Toyota_Prius+', 'Toyota_RAV4',
       'Toyota_Urbancruiser', 'Toyota_Verso', 'Toyota_Verso S',
       'Toyota_Yaris', 'Toyota_iQ', 'Vauxhall_ADAM', 'Vauxhall_Agila',
       'Vauxhall_Ampera', 'Vauxhall_Antara', 'Vauxhall_Astra',
       'Vauxhall_Astra GTC', 'Vauxhall_Cascada', 'Vauxhall_Corsa',
       'Vauxhall_Crossland X', 'Vauxhall_Grandland X',
       'Vauxhall_Insignia', 'Vauxhall_Meriva', 'Vauxhall_Mokka',
       'Vauxhall_Mokka X', 'Vauxhall_Signum', 'Vauxhall_Tigra',
       'Vauxhall_VXR8', 'Vauxhall_Vectra', 'Vauxhall_Viva',
       'Vauxhall_Vivaro', 'Vauxhall_Zafira', 'Vauxhall_Zafira Tourer',
       'Volkswagen_Amarok', 'Volkswagen_Arteon', 'Volkswagen_Beetle',
       'Volkswagen_Bora', 'Volkswagen_CC', 'Volkswagen_Caddy Maxi',
       'Volkswagen_Caddy Maxi Life', 'Volkswagen_California',
       'Volkswagen_Caravelle', 'Volkswagen_Eos', 'Volkswagen_Fox',
       'Volkswagen_Golf', 'Volkswagen_Golf Plus', 'Volkswagen_Golf SV',
       'Volkswagen_Jetta', 'Volkswagen_Passat', 'Volkswagen_Phaeton',
       'Volkswagen_Polo', 'Volkswagen_Scirocco', 'Volkswagen_Sharan',
       'Volkswagen_T-Roc', 'Volkswagen_Tiguan',
       'Volkswagen_Tiguan Allspace', 'Volkswagen_Touareg',
       'Volkswagen_Touran', 'Volkswagen_Transporter',
       'Volkswagen_Transporter Shuttle',
       'Volkswagen_Transporter Sportline', 'Volkswagen_up!', 'Volvo_C30',
       'Volvo_C70', 'Volvo_S40', 'Volvo_S60', 'Volvo_S80', 'Volvo_S90',
       'Volvo_V40', 'Volvo_V40 Cross Country', 'Volvo_V50', 'Volvo_V60',
       'Volvo_V60 Cross Country', 'Volvo_V70', 'Volvo_V90',
       'Volvo_V90 Cross Country', 'Volvo_XC60', 'Volvo_XC70',
       'Volvo_XC90']
VEHICLE_MODEL = [f"Model-{m}" for m in VEHICLE_MODEL]

color = [
    "Color-Black",
    "Color-Blue",
    "Color-Brown",
    "Color-Green",
    "Color-Grey",
    "Color-Orange",
    "Color-Red",
    "Color-Silver",
    "Color-White",
    "Color-Yellow",
]

ATTRIBUTES = VEHICLE_MAKE + VEHICLE_MODEL + color

def getGroup():
    getGroupName = lambda s: '-'.join(s.split('-')[:-1])
    groups = set([getGroupName(attr) for attr in ATTRIBUTES])
    groups = {
        group: [attr for attr in ATTRIBUTES if group in attr] for group in groups
    }
    group_order = ["Color", "Make", "Model"]
    groups = {group: groups[group] for group in group_order}
    return groups
GRUOPS = getGroup()

DEMO_IMGS = [str(p) for p in Path("samples/var").glob('*')]

DEMO_MODELS = [
    "EMO.onnx",
    "contras.onnx",
    "var.onnx",
    "mobile.onnx",
]
DEMO_MODEL = DEMO_MODELS[0]

VEHICLE_COLOR = {
    0: (  0,   0,   0),  # Black
    1: (255,   0,   0),  # Blue
    2: ( 42,  42, 165),  # Brown
    3: (  0, 128,   0),  # Green
    4: (128, 128, 128),  # Grey
    5: (  0, 165, 255),  # Orange
    6: (  0,   0, 255),  # Red
    7: (192, 192, 192),  # Silver
    8: (255, 255, 255),  # White
    9: (  0, 255, 255),  # Yellow
}
